<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\PhoneBook.Domain\PhoneBook.Domain.csproj" />
    <ProjectReference Include="..\..\Infrastructure\PhoneBook.Infrastructure\PhoneBook.Infrastructure.csproj" />
  </ItemGroup>

</Project>
